/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unimet.saman_productions;

import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import unimet.saman_productions.drives.DriveManager;
import unimet.saman_productions.drives.Drive;
import unimet.saman_productions.employees.*;
import unimet.saman_productions.studios.CartoonNetwork;
import unimet.saman_productions.studios.StarChannel;

/**
 *
 * @author USUARIO
 */
public class MainFrame extends javax.swing.JFrame {
    public DriveManager driveManager;
    public LectorDeTxt lector = new LectorDeTxt();
    public String pathTxt;
    public Integer guionistasNumber;
    public Integer designersNumber;
    public Integer animadoresNumber;
    public Integer actoresDoblaje;
    public Integer guionistasPlotTwist;
    public Integer ensambladoresNumber;
    public Integer segundosDay;
    public Integer deadline;
    private StarChannel starchannel;
    private CartoonNetwork cartoonNetwork;
    private boolean botonClick = false; 

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        stopSimulation.setEnabled(false);
        startSimulation.setEnabled(false);
        actualizeData.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ModificarDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        ensambladores = new javax.swing.JTextField();
        guionistas = new javax.swing.JTextField();
        animadores = new javax.swing.JTextField();
        CargarTxt = new javax.swing.JButton();
        plotTwist = new javax.swing.JTextField();
        doblaje = new javax.swing.JTextField();
        designers = new javax.swing.JTextField();
        actualizeData = new javax.swing.JButton();
        seconds = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        deadlineTxt = new javax.swing.JTextField();
        stopSimulation = new javax.swing.JButton();
        startSimulation = new javax.swing.JButton();
        CapitulosDrive = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        screenwriterDriveSizeCN = new javax.swing.JTextField();
        setDesignerDriveSizeCN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        animatorDriveSizeCN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        voiceActorDriveSizeCN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        plotTwistDriveSizeCN = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        chaptersScreenWriterCN = new javax.swing.JLabel();
        chapterVoiceCN = new javax.swing.JLabel();
        chaptersPTWriterCN = new javax.swing.JLabel();
        chaptersSceneCN = new javax.swing.JLabel();
        chaptersAnimatorCN = new javax.swing.JLabel();
        deadLineCN = new javax.swing.JLabel();
        pmStatusCN = new javax.swing.JLabel();
        faultsPMCN = new javax.swing.JLabel();
        directorCN = new javax.swing.JLabel();
        StarChannel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        maxStarScreenWriter = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        capitulosStar = new javax.swing.JLabel();
        SceneChapters = new javax.swing.JLabel();
        DoblajeChapters = new javax.swing.JLabel();
        AnimatorChapters = new javax.swing.JLabel();
        plotTwistChapters = new javax.swing.JLabel();
        deadLineSC = new javax.swing.JLabel();
        pmStatusSC = new javax.swing.JLabel();
        faultsPMStar = new javax.swing.JLabel();
        directorStar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));

        ModificarDatos.setBackground(new java.awt.Color(153, 204, 255));
        ModificarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de guionistas:");
        ModificarDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad de diseñadores:");
        ModificarDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Cantidad de animadores: ");
        ModificarDatos.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Cantidad de actores de doblaje: ");
        ModificarDatos.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Cantidad de guionistas plot tiwst: ");
        ModificarDatos.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Cantidad de ensambladores:");
        ModificarDatos.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        ensambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensambladoresActionPerformed(evt);
            }
        });
        ModificarDatos.add(ensambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 80, -1));

        guionistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guionistasActionPerformed(evt);
            }
        });
        ModificarDatos.add(guionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 80, -1));

        animadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animadoresActionPerformed(evt);
            }
        });
        ModificarDatos.add(animadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 80, -1));

        CargarTxt.setBackground(new java.awt.Color(255, 255, 255));
        CargarTxt.setForeground(new java.awt.Color(0, 0, 0));
        CargarTxt.setText("Cargar Datos del TXT");
        CargarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarTxtActionPerformed(evt);
            }
        });
        ModificarDatos.add(CargarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, -1));

        plotTwist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwistActionPerformed(evt);
            }
        });
        ModificarDatos.add(plotTwist, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 80, -1));

        doblaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doblajeActionPerformed(evt);
            }
        });
        ModificarDatos.add(doblaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 80, -1));

        designers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designersActionPerformed(evt);
            }
        });
        ModificarDatos.add(designers, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 80, -1));

        actualizeData.setBackground(new java.awt.Color(255, 255, 255));
        actualizeData.setForeground(new java.awt.Color(0, 0, 0));
        actualizeData.setText("Actualizar Datos");
        actualizeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizeDataActionPerformed(evt);
            }
        });
        ModificarDatos.add(actualizeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 290, -1));

        seconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondsActionPerformed(evt);
            }
        });
        ModificarDatos.add(seconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Deadline de la Entrega");
        ModificarDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Duración en segundos de un día");
        ModificarDatos.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        deadlineTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineTxtActionPerformed(evt);
            }
        });
        ModificarDatos.add(deadlineTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 120, -1));

        stopSimulation.setBackground(new java.awt.Color(0, 0, 51));
        stopSimulation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stopSimulation.setForeground(new java.awt.Color(255, 255, 255));
        stopSimulation.setText("Detener simulación");
        stopSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopSimulationActionPerformed(evt);
            }
        });
        ModificarDatos.add(stopSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 210, -1));

        startSimulation.setBackground(new java.awt.Color(0, 0, 51));
        startSimulation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startSimulation.setForeground(new java.awt.Color(255, 255, 255));
        startSimulation.setText("Comenzar simulación");
        startSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationActionPerformed(evt);
            }
        });
        ModificarDatos.add(startSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 210, -1));

        jTabbedPane1.addTab("Modificar Datos", ModificarDatos);

        CapitulosDrive.setBackground(new java.awt.Color(153, 204, 255));
        CapitulosDrive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CARTOON NETWORK");
        CapitulosDrive.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        screenwriterDriveSizeCN.setText(String.valueOf(Screenwriter.DRIVE_SIZE));
        CapitulosDrive.add(screenwriterDriveSizeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, -1));

        setDesignerDriveSizeCN.setText(String.valueOf(SetDesigner.DRIVE_SIZE));
        CapitulosDrive.add(setDesignerDriveSizeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("DRIVE DISEÑADOR DE ESCENARIOS");
        CapitulosDrive.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 10));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Capacidad máxima de capítulos:");
        CapitulosDrive.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad de capítulos existentes:");
        CapitulosDrive.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Capacidad máxima de capítulos:");
        CapitulosDrive.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("DRIVE ACTORES DOBLAJE");
        CapitulosDrive.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 20));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cantidad de capítulos existentes:");
        CapitulosDrive.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("DRIVE ANIMADOR");
        CapitulosDrive.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 10));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cantidad de capítulos existentes:");
        CapitulosDrive.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Capacidad máxima de capítulos:");
        CapitulosDrive.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        animatorDriveSizeCN.setText(String.valueOf(Animator.DRIVE_SIZE));
        animatorDriveSizeCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animatorDriveSizeCNActionPerformed(evt);
            }
        });
        CapitulosDrive.add(animatorDriveSizeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("DRIVE GUIONISTA");
        CapitulosDrive.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cantidad de capítulos existentes:");
        CapitulosDrive.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 200, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Capacidad máxima de capítulos:");
        CapitulosDrive.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 200, -1));

        voiceActorDriveSizeCN.setText(String.valueOf(VoiceActor.DRIVE_SIZE));
        CapitulosDrive.add(voiceActorDriveSizeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("DRIVE PLOT TWIST");
        CapitulosDrive.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 20));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Cantidad de capítulos existentes:");
        CapitulosDrive.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 200, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Capacidad máxima de capítulos:");
        CapitulosDrive.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 200, -1));

        plotTwistDriveSizeCN.setText(String.valueOf(PlotTwistWriter.DRIVE_SIZE));
        plotTwistDriveSizeCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotTwistDriveSizeCNActionPerformed(evt);
            }
        });
        CapitulosDrive.add(plotTwistDriveSizeCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 90, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Días para la entrega: ");
        CapitulosDrive.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Capítulos listos:");
        CapitulosDrive.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));
        CapitulosDrive.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 80, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Capítulos publicados:");
        CapitulosDrive.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));
        CapitulosDrive.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 70, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 102));
        jLabel56.setText("PROJECT MANAGER");
        CapitulosDrive.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));

        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Qué está haciendo:");
        CapitulosDrive.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Cantidad de faltas");
        CapitulosDrive.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Dinero descontado");
        CapitulosDrive.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        CapitulosDrive.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 140, -1));

        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Qué está haciendo:");
        CapitulosDrive.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 102));
        jLabel61.setText("DIRECTOR");
        CapitulosDrive.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("Ingresos:");
        CapitulosDrive.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });
        CapitulosDrive.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 80, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Costos:");
        CapitulosDrive.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));
        CapitulosDrive.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 80, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Utilidades:");
        CapitulosDrive.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, -1, -1));
        CapitulosDrive.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 80, -1));
        CapitulosDrive.add(chaptersScreenWriterCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));
        CapitulosDrive.add(chapterVoiceCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));
        CapitulosDrive.add(chaptersPTWriterCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));
        CapitulosDrive.add(chaptersSceneCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));
        CapitulosDrive.add(chaptersAnimatorCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));
        CapitulosDrive.add(deadLineCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));
        CapitulosDrive.add(pmStatusCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));
        CapitulosDrive.add(faultsPMCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));
        CapitulosDrive.add(directorCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jTabbedPane1.addTab("Cartoon Network", CapitulosDrive);

        StarChannel.setBackground(new java.awt.Color(153, 204, 255));
        StarChannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("STAR CHANNEL");
        StarChannel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("PROJECT MANAGER");
        StarChannel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Cantidad de capítulos existentes:");
        StarChannel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Cantidad máxima de capítulos:");
        StarChannel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        maxStarScreenWriter.setText(String.valueOf(Screenwriter.DRIVE_SIZE));
        maxStarScreenWriter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxStarScreenWriterActionPerformed(evt);
            }
        });
        StarChannel.add(maxStarScreenWriter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 80, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("DRIVE DISEÑADOR DE ESCENARIOS ");
        StarChannel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Cantidad de capítulos existentes:");
        StarChannel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Cantidad máxima de capítulos:");
        StarChannel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jTextField13.setText(String.valueOf(SetDesigner.DRIVE_SIZE));
        StarChannel.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("DRIVE ANIMADORES");
        StarChannel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Cantidad de capítulos existentes:");
        StarChannel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Cantidad máxima de capítulos:");
        StarChannel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextField15.setText(String.valueOf(Animator.DRIVE_SIZE));
        StarChannel.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("DRIVE ACTORES DOBLAJE");
        StarChannel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Cantidad de capítulos existentes:");
        StarChannel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Cantidad máxima de capítulos:");
        StarChannel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jTextField17.setText(String.valueOf(VoiceActor.DRIVE_SIZE));
        StarChannel.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 80, -1));

        jTextField19.setText(String.valueOf(PlotTwistWriter.DRIVE_SIZE));
        StarChannel.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 80, -1));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Cantidad máxima de capítulos:");
        StarChannel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Cantidad de capítulos existentes:");
        StarChannel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 102));
        jLabel35.setText("DRIVE PLOT TWIST");
        StarChannel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Días para la entrega: ");
        StarChannel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 102));
        jLabel37.setText("DRIVE GUIONISTA ");
        StarChannel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Qué está haciendo:");
        StarChannel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Cantidad de faltas");
        StarChannel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Dinero descontado");
        StarChannel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        StarChannel.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 140, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 102));
        jLabel38.setText("DIRECTOR");
        StarChannel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 20));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Qué está haciendo:");
        StarChannel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Capítulos publicados:");
        StarChannel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));
        StarChannel.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 70, -1));
        StarChannel.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 80, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Capítulos listos:");
        StarChannel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Ingresos:");
        StarChannel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        StarChannel.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 80, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Costos:");
        StarChannel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));
        StarChannel.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 80, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Utilidades:");
        StarChannel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, -1, -1));
        StarChannel.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 80, -1));

        capitulosStar.setForeground(new java.awt.Color(0, 0, 0));
        StarChannel.add(capitulosStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, -1));
        StarChannel.add(SceneChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
        StarChannel.add(DoblajeChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));
        StarChannel.add(AnimatorChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));
        StarChannel.add(plotTwistChapters, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 40, 20));
        StarChannel.add(deadLineSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 40, 10));
        StarChannel.add(pmStatusSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));
        StarChannel.add(faultsPMStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));
        StarChannel.add(directorStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jTabbedPane1.addTab("Star Channel", StarChannel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animatorDriveSizeCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animatorDriveSizeCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animatorDriveSizeCNActionPerformed

    private void stopSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSimulationActionPerformed
        starchannel.stop();
        cartoonNetwork.stop();
    }//GEN-LAST:event_stopSimulationActionPerformed

    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationActionPerformed
        botonClick = true;
        deadlineTxt.setEnabled(false);
        seconds.setEnabled(false);
        starchannel = new StarChannel(lector.getDeadline(), "SC", Integer.parseInt(seconds.getText()));
        EmployeeManager employeeManagerStar = new EmployeeManager(starchannel, lector.getGuionistas(),
                lector.getDesginers(), lector.getAnimadores(), lector.getActoresDoblaje(),
                lector.getGuionistasPlotTwist(), lector.getEnsambladores());
        StudioView studioView = new StudioView(starchannel, this);
        starchannel.start(employeeManagerStar);

        cartoonNetwork = new CartoonNetwork(lector.getDeadline(), "CN", Integer.parseInt(seconds.getText()));
        EmployeeManager employeeManagerCartoon = new EmployeeManager(cartoonNetwork, lector.getGuionistas(),
                lector.getDesginers(), lector.getAnimadores(), lector.getActoresDoblaje(),
                lector.getGuionistasPlotTwist(), lector.getEnsambladores());
        StudioView studioViewCartoon = new StudioView(cartoonNetwork, this);
        cartoonNetwork.start(employeeManagerCartoon);
    }//GEN-LAST:event_startSimulationActionPerformed

    private void maxStarScreenWriterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxStarScreenWriterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxStarScreenWriterActionPerformed

    private void plotTwistDriveSizeCNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plotTwistDriveSizeCNActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_plotTwistDriveSizeCNActionPerformed

    private void pmStatusSCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pmStatusSCActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pmStatusSCActionPerformed

    private void directorStarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_directorStarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_directorStarActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField28ActionPerformed

    private void guionistasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_guionistasActionPerformed
        guionistasNumber = Integer.valueOf(guionistas.getText());
    }// GEN-LAST:event_guionistasActionPerformed

    public void setCapitulosStar(String texto) {
        capitulosStar.setText(texto);
    }

    public void setSceneChapters(String texto) {
        SceneChapters.setText(texto);
    }

    public void setAnimatorChapters(String texto) {
        AnimatorChapters.setText(texto);
    }

    public void setDoblajeChapters(String texto) {
        DoblajeChapters.setText(texto);
    }

    public void setPlotTwistChapters(String texto) {
        plotTwistChapters.setText(texto);
    }

    public void setScreenWriterCN(String texto) {
        chaptersScreenWriterCN.setText(texto);
    }

    public void setSceneChaptersCN(String texto) {
        chaptersSceneCN.setText(texto);
    }

    public void setAnimatorChapCN(String texto) {
        chaptersAnimatorCN.setText(texto);
    }

    public void setChaptersVACN(String texto) {
        chapterVoiceCN.setText(texto);
    }

    public void setChaptersPTWCN(String texto) {
        chaptersPTWriterCN.setText(texto);
    }

    public void setPmStatusSC(String texto) {
        pmStatusSC.setText(texto);
    }

    public void setFaultsPMSC(String texto) {
        faultsPMStar.setText(texto);
    }

    public void setDeadLineSC(String texto) {
        deadLineSC.setText(texto);
    }

    public void setDeadLineCN(String texto) {
        deadLineCN.setText(texto);
    }

    public void setFaultsPMCN(String texto) {
        faultsPMCN.setText(texto);
    }

    public void setPMStatusCN(String texto) {
        pmStatusCN.setText(texto);
    }
    
    public void setDirectorStatusCN(String texto) {
        directorStar.setText(texto);
    }
    
    public void setDirectorStatusSC(String texto) {
        directorCN.setText(texto);
    }
    
    private void CargarTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CargarTxtActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            pathTxt = archivo.getAbsolutePath();
            lector.leerArchivo(pathTxt);
            guionistas.setText(lector.getGuionistas().toString());
            animadores.setText(lector.getAnimadores().toString());
            designers.setText(lector.getDesginers().toString());
            ensambladores.setText(lector.getEnsambladores().toString());
            doblaje.setText(lector.getActoresDoblaje().toString());
            plotTwist.setText(lector.getGuionistasPlotTwist().toString());
            seconds.setText(lector.getSegundosDay().toString());
            deadlineTxt.setText(lector.getDeadline().toString());
            stopSimulation.setEnabled(true);
            startSimulation.setEnabled(true);
            actualizeData.setEnabled(true);
        }

    }// GEN-LAST:event_CargarTxtActionPerformed

    private void designersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_designersActionPerformed
        designersNumber = Integer.valueOf(designers.getText());
    }// GEN-LAST:event_designersActionPerformed

    private void actualizeDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_actualizeDataActionPerformed
        if (guionistas != null && designers != null && animadores != null && doblaje != null && plotTwist != null
                && ensambladores != null && !guionistas.getText().equals("") && !designers.getText().equals("")
                && !animadores.getText().equals("") &&
                !doblaje.getText().equals("") && !plotTwist.getText().equals("")
                && !ensambladores.getText().equals("")) {
            guionistasNumber = Integer.valueOf(guionistas.getText());
            designersNumber = Integer.valueOf(designers.getText());
            animadoresNumber = Integer.valueOf(animadores.getText());
            actoresDoblaje = Integer.valueOf(doblaje.getText());
            guionistasPlotTwist = Integer.valueOf(plotTwist.getText());
            ensambladoresNumber = Integer.valueOf(ensambladores.getText());
            segundosDay = Integer.valueOf(seconds.getText());
            deadline = Integer.valueOf(deadlineTxt.getText());

            if (guionistasNumber != 0 && designersNumber != 0 && animadoresNumber != 0 && actoresDoblaje != 0
                    && guionistasPlotTwist != 0 && ensambladoresNumber != 0) {
                lector.actualizarDatos(pathTxt, guionistasNumber, designersNumber, animadoresNumber, actoresDoblaje,
                        guionistasNumber, ensambladoresNumber, segundosDay,
                        deadline);
                if(botonClick){
                    starchannel.getEmployeeManager().updateEmployeeNumbers(guionistasNumber, designersNumber,
                            animadoresNumber, actoresDoblaje, guionistasPlotTwist, ensambladoresNumber);
                    cartoonNetwork.getEmployeeManager().updateEmployeeNumbers(guionistasNumber, designersNumber,
                            animadoresNumber, actoresDoblaje, guionistasPlotTwist, ensambladoresNumber);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: Los campos no pueden tener un valor igual a cero.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error: Los campos no pueden estar vacï¿½os.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_actualizeDataActionPerformed

    private void animadoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_animadoresActionPerformed
        animadoresNumber = Integer.valueOf(animadores.getText());
    }// GEN-LAST:event_animadoresActionPerformed

    private void ensambladoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ensambladoresActionPerformed
        ensambladoresNumber = Integer.valueOf(ensambladores.getText());
    }// GEN-LAST:event_ensambladoresActionPerformed

    private void doblajeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doblajeActionPerformed
        actoresDoblaje = Integer.valueOf(doblaje.getText());
    }// GEN-LAST:event_doblajeActionPerformed

    private void plotTwistActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plotTwistActionPerformed
        guionistasPlotTwist = Integer.valueOf(plotTwist.getText());
    }// GEN-LAST:event_plotTwistActionPerformed

    private void secondsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_secondsActionPerformed
        segundosDay = Integer.valueOf(seconds.getText());
    }// GEN-LAST:event_secondsActionPerformed

    private void deadlineTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deadlineTxtActionPerformed
        deadline = Integer.valueOf(deadlineTxt.getText());
    }// GEN-LAST:event_deadlineTxtActionPerformed

    private void chaptersScreenWriterCNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chaptersScreenWriterCNActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chaptersScreenWriterCNActionPerformed

    private void pmStatusCNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pmStatusCNActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pmStatusCNActionPerformed

    private void directorStar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_directorStar1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_directorStar1ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimatorChapters;
    private javax.swing.JPanel CapitulosDrive;
    private javax.swing.JButton CargarTxt;
    private javax.swing.JLabel DoblajeChapters;
    private javax.swing.JPanel ModificarDatos;
    private javax.swing.JLabel SceneChapters;
    private javax.swing.JPanel StarChannel;
    private javax.swing.JButton actualizeData;
    private javax.swing.JTextField animadores;
    private javax.swing.JTextField animatorDriveSizeCN;
    private javax.swing.JLabel capitulosStar;
    private javax.swing.JLabel chapterVoiceCN;
    private javax.swing.JLabel chaptersAnimatorCN;
    private javax.swing.JLabel chaptersPTWriterCN;
    private javax.swing.JLabel chaptersSceneCN;
    private javax.swing.JLabel chaptersScreenWriterCN;
    private javax.swing.JLabel deadLineCN;
    private javax.swing.JLabel deadLineSC;
    private javax.swing.JTextField deadlineTxt;
    private javax.swing.JTextField designers;
    private javax.swing.JLabel directorCN;
    private javax.swing.JLabel directorStar;
    private javax.swing.JTextField doblaje;
    private javax.swing.JTextField ensambladores;
    private javax.swing.JLabel faultsPMCN;
    private javax.swing.JLabel faultsPMStar;
    private javax.swing.JTextField guionistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField maxStarScreenWriter;
    private javax.swing.JTextField plotTwist;
    private javax.swing.JLabel plotTwistChapters;
    private javax.swing.JTextField plotTwistDriveSizeCN;
    private javax.swing.JLabel pmStatusCN;
    private javax.swing.JLabel pmStatusSC;
    private javax.swing.JTextField screenwriterDriveSizeCN;
    private javax.swing.JTextField seconds;
    private javax.swing.JTextField setDesignerDriveSizeCN;
    private javax.swing.JButton startSimulation;
    private javax.swing.JButton stopSimulation;
    private javax.swing.JTextField voiceActorDriveSizeCN;
    // End of variables declaration//GEN-END:variables
}
